name: Initial Build Workflow
on: push
jobs:
  Build-Unity-Version: 
    name: Build Unity Project
    runs-on: windows-latest
    steps:
      #Checkout code without LFS
      - uses: actions/checkout@v3
        name: Checkout Code

      #Cache
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashfiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      #Build
      - name: Build Project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: windows
      
      #Slack
      - name: Send Slack Message
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          payload: |
            {
              "text": "Deployment started (In Progress)",
              "attachments": [
                {
                  "pretext": "Deployment started",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "In Progress"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
      - uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment finished (Completed)",
              "attachments": [
                {
                  "pretext": "Deployment finished",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Completed"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      #Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

    