name: Build Project

on: [push]

env: 
  ITCH_USERNAME: evil-josh
  ITCH_GAME_ID: testing-github-actions

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    # This stops builds that are in-progress once a new commit comes in
    concurrency: 
      group: unity-build
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      # Posting an "in progress" message to slack
      - name: Post status to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          payload: |
            {
              "text": "Deployment Started.",
              "attachments": [
                {
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Build in Progress: \n https://github.com/jAdriaanse/test_GithubActions/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            } 
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      # Cache
      - uses: actions/cache@v2
        with:
          #path: C:\Users\User-Pc\Desktop\Synology\Renderheads\Repos\test_GithubActions\github_actions_test
          path: "./github_actions_test/Library"
          key: unity-library-forCaching

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          # Comment this out if you're using a pro license
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          # Un-Comment the following lines if you're using a pro license
          # UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          # UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          # UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
        with:
          projectPath: "./github_actions_test"
          targetPlatform: StandaloneWindows64
        # Return License (Un-Comment if you're using a pro license)
        #- name: Return license
        #  uses: game-ci/unity-return-license@v1
        #  if: always()

      # Output
      - uses: actions/upload-artifact@v2
        with:
          name: Build
          path: build

      
      # Posting an "completed" message to slack
      - name: Post success to a Slack channel
        if: ${{ success() }}
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment Finished.",
              "attachments": [
                {
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Build Completed: \n https://github.com/jAdriaanse/test_GithubActions/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      # Posting an "cancelled" message to slack
      - name: Post cancel to a Slack channel
        if: ${{ cancelled() }}
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment Canceled.",
              "attachments": [
                {
                  "color": "8b0000",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Build Canceled: \n https://github.com/jAdriaanse/test_GithubActions/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}

      # Posting an "failure" message to slack
      - name: Post failure to a Slack channel
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@v1.21.0
        with:
          channel-id: "C03V4JPBFM1"
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "Deployment Failed.",
              "attachments": [
                {
                  "color": "8b0000",
                  "fields": [
                    {
                      "title": "Status",
                      "short": true,
                      "value": "Build Failed: \n https://github.com/jAdriaanse/test_GithubActions/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN}}
  
  # publish:
  #   name: Upload to Itch
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: true
  #     matrix:
  #       channel:
  #         - windows
  #         - mac
  #   runs-on: ubuntu-latest
  #   name: Deploy - Itch.io ${{ matrix.template }}
  #   steps:
  #     - uses: actions/download-artifact@v2.0.8
  #       with:
  #         name: ${{ matrix.channel }}
  #         path: build/${{ matrix.channel }}
  #     - uses: KikimoraGames/itch-publish@v0.0.3
  #       with:
  #         butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
  #         gameData: ./build/${{ matrix.template }}
  #         itchUsername: ${{ env.ITCH_USERNAME }}
  #         itchGameId: ${{ env.ITCH_GAME_ID }}
  #         buildChannel: ${{ matrix.channel }}
  #         buildNumber: ${{ needs.version.outputs.version_hash }}